spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
  application:
    name: trainer-workload-service
  activemq:
    broker-url: ${spring.activemq.broker-url}
    user: ${spring.activemq.user}
    password: ${spring.activemq.password}
  config:
    import: "classpath:env.yml"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${spring.data.mongodb.database}
      auto-index-creation: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true

server:
  port: 8081

token:
  secret:
    key: ${token.secret.key}
